# Generated by Django 3.2.9 on 2021-11-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_jogador_linha', models.IntegerField(choices=[(5, 5), (6, 6), (7, 7), (8, 8), (8, 8), (9, 9), (10, 10)], verbose_name='Quantidade de jogador no time')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome ou Apelido')),
                ('e_golero', models.BooleanField(default=False, verbose_name='É Goleiro??')),
            ],
        ),
    ]
